# Install and test

name: Tests

on:
    push:
        branches:
            - develop
            - master
    pull_request:
        branches:
            - develop
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install dependencies
              run: python -m pip install -r requirements.txt .[dev]
            - name: Check static typing
              run: python -m mypy nbaspa_app
            - name: Run flake8
              run: python -m flake8 nbaspa_app
